"""
EC093 — Adsorption Chiller — F2a Physics-Lumped (Adsorption Kinetics)
====================================================================

A 0D dynamic model of a single-stage, two-bed silica-gel / water adsorption
chiller.  Two identical adsorbent beds operate 180 deg out of phase: while
one bed *adsorbs* refrigerant vapour from the evaporator (producing the
cooling effect at the chilled-water temperature) the other *desorbs* (is
regenerated by hot driving water and rejects vapour to the condenser).
Beds swap roles every half-cycle.

Physics
-------
1. Adsorption equilibrium — **Dubinin–Astakhov (D-A)** isotherm:

       w*(T_bed, T_sat) = W0 * exp( -D * (R*T_bed * ln(P_sat(T_sat)/P(T_bed)))^n )

   Written with the adsorption potential A = R*T*ln(P_sat/P):

       w* = W0 * exp( -D * A^n )

   where the vapour pressure ratio is set by the saturation pressure at the
   evaporator (adsorption) or condenser (desorption) temperature relative to
   the saturation pressure at the bed temperature.  (Chua et al. 1999.)

2. Sorption rate — **Linear Driving Force (LDF)** kinetics:

       dw/dt = k_LDF (T_bed) * (w*(T_bed) - w)
       k_LDF = k_inf * exp( -Ea_surf / (R * T_bed) )      (Sakoda–Suzuki form)

   This is the lumped surface-diffusion approximation used by Saha (1995).

3. Lumped bed energy balance (one ODE per bed):

       (m_sg*cp_sg + m_metal*cp_metal + m_sg*w*cp_water_liq) dT_bed/dt
            = m_sg * dH_ads * dw/dt                 (sorption heat, + on ads.)
            + m_sg * dw/dt * cp_v * (T_sat - T_bed) (sensible vapour, ads.)
            + UA_bed * eps * (T_htf_in - T_bed)     (heat-transfer-fluid load)

   On adsorption dw/dt>0 releases heat (rejected to cooling water); on
   desorption dw/dt<0 absorbs heat (supplied by hot water).

4. Saturation pressure of water — Antoine/Clausius form (Rogers & Mayhew).

Outputs
-------
   * cooling power   Q_evap   = m_sg * (-dw/dt)_ads * h_fg   (refrigerant
                               evaporated to feed the adsorbing bed)
   * driving heat    Q_des    = hot-water duty into the desorbing bed
   * thermal COP     = ∫Q_evap / ∫Q_des  over a full cycle  (~0.3–0.6)
   * specific cooling power (SCP)  = mean Q_evap / m_sg

Energy / mass conservation are enforced: the refrigerant mass desorbed over a
full cycle equals that adsorbed (cyclic steady state), and the driving heat is
bounded below by the evaporator load (COP < ~0.85, well under the absorption
double-effect ceiling).

References
----------
   Saha, B.B., Boelman, E.C., Kashiwagi, T. (1995). "Computational analysis of
       an advanced adsorption-refrigeration cycle." Heat Recovery Systems & CHP
       15(6), 581-590. Also Int. J. Refrigeration 18(4), 254-262.
   Chua, H.T., Ng, K.C., Malek, A., Kashiwagi, T., Akisawa, A., Saha, B.B.
       (1999). "Modeling the performance of two-bed silica gel-water adsorption
       chillers." Int. J. Heat Mass Transfer 42, 3613-3620.
   Wang, R.Z., Oliveira, R.G. (2006). "Adsorption refrigeration — an efficient
       way to make good use of waste heat and solar energy." Prog. Energy
       Combust. Sci. 32, 424-458.

Pure Python + NumPy + SciPy (solve_ivp).  No CoolProp / heavy deps.
"""

import numpy as np
from scipy.integrate import solve_ivp


def p_sat_water(T_K):
    """Saturation pressure of water [Pa] from temperature [K].

    Antoine equation, coefficients valid ~273-373 K (Rogers & Mayhew steam
    tables / NIST).  log10(P_bar) = A - B/(C + T_C).
    """
    T_C = np.asarray(T_K, dtype=float) - 273.15
    # Antoine (water, 1-100 C), P in mmHg
    A, B, C = 8.07131, 1730.63, 233.426
    log10_p_mmHg = A - B / (C + T_C)
    p_mmHg = 10.0 ** log10_p_mmHg
    return p_mmHg * 133.322  # mmHg -> Pa


class AdsorptionChillerF2a:
    """Two-bed silica-gel/water adsorption chiller — D-A + LDF + thermal ODE."""

    def __init__(self, params: dict):
        u = params["unit"]
        g = lambda k: u[k]["value"]
        self.m_sg = g("m_sg")
        self.W0 = g("W0")
        self.D_DA = g("D_DA")
        self.n_DA = g("n_DA")
        self.k_inf = g("k_LDF_inf")
        self.Ea_surf = g("Ea_surf")
        self.dH_ads = g("dH_ads")
        self.h_fg = g("h_fg")
        self.cp_w_liq = g("cp_water_liq")
        self.cp_w_vap = g("cp_water_vap")
        self.cp_sg = g("cp_sg")
        self.cp_metal = g("cp_metal")
        self.m_metal = g("m_metal")
        self.R_univ = g("R_univ")
        self.UA_bed = g("UA_bed")
        self.m_dot_hw = g("m_dot_hw")
        # default operating temperatures (deg C)
        self.T_hot_c = g("T_hot")
        self.T_cool_c = g("T_cool")
        self.T_chilled_c = g("T_chilled")
        self.t_half = g("t_half_cycle")

    # ----- equilibrium & kinetics -------------------------------------
    def w_equilibrium(self, T_bed_K, T_sat_source_K):
        """D-A equilibrium uptake w* [kg/kg].

        T_sat_source_K : evaporator T (adsorption) or condenser T (desorption);
            sets the imposed vapour pressure P = p_sat(T_sat_source).
        T_bed_K : adsorbent temperature.
        Adsorption potential A = R/M * T_bed * ln(p_sat(T_bed)/P).
        """
        P_imposed = p_sat_water(T_sat_source_K)
        P_bed_sat = p_sat_water(T_bed_K)
        # adsorption potential per unit mass [J/kg]; guard ln domain
        ratio = np.maximum(P_bed_sat / np.maximum(P_imposed, 1.0), 1e-12)
        # Molar adsorption potential A = R*T*ln(p_sat(T_bed)/P) in J/mol
        # (Dubinin-Astakhov coefficient D_DA is calibrated against the molar
        #  potential, Chua et al. 1999).
        A_pot = self.R_univ * np.asarray(T_bed_K, float) * np.log(ratio)
        A_pot = np.maximum(A_pot, 0.0)  # below source-sat -> full capacity
        w_star = self.W0 * np.exp(-self.D_DA * A_pot ** self.n_DA)
        return np.clip(w_star, 0.0, self.W0)

    def k_ldf(self, T_bed_K):
        """LDF mass-transfer coefficient [1/s] (Sakoda-Suzuki form)."""
        return self.k_inf * np.exp(-self.Ea_surf / (self.R_univ * np.asarray(T_bed_K, float)))

    # ----- single-bed dynamics during one half-cycle -------------------
    def _bed_rhs(self, t, y, mode, T_htf_in_K, T_sat_source_K):
        """ODE RHS for [T_bed, w] over one half-cycle.

        mode = 'ads'  -> adsorption (cooling): T_htf_in = T_cool
        mode = 'des'  -> desorption (regen):   T_htf_in = T_hot
        T_sat_source_K = evaporator T (ads) or condenser T (des).
        """
        T_bed, w = y
        w = max(w, 0.0)
        w_star = float(self.w_equilibrium(T_bed, T_sat_source_K))
        dwdt = self.k_ldf(T_bed) * (w_star - w)

        # effective HX effectiveness from UA and flow capacity rate
        C_hw = self.m_dot_hw * self.cp_w_liq
        ntu = self.UA_bed / max(C_hw, 1e-9)
        eps = 1.0 - np.exp(-ntu)
        Q_hx = eps * C_hw * (T_htf_in_K - T_bed)  # W into bed

        # sorption heat: released (+) on adsorption, absorbed on desorption
        Q_sorp = self.m_sg * self.dH_ads * dwdt
        # sensible heat carried by incoming vapour during adsorption
        Q_vap = self.m_sg * max(dwdt, 0.0) * self.cp_w_vap * (T_sat_source_K - T_bed)

        C_bed = (self.m_sg * self.cp_sg + self.m_metal * self.cp_metal
                 + self.m_sg * w * self.cp_w_liq)
        dTdt = (Q_sorp + Q_vap + Q_hx) / C_bed
        return [dTdt, dwdt]

    def run_half_cycle(self, mode, T_bed0_K, w0, n_eval=60):
        """Integrate one bed through one half-cycle. Returns dict of arrays."""
        if mode == "ads":
            T_htf_in = self.T_cool_c + 273.15
            T_sat_source = self.T_chilled_c + 273.15   # evaporator
        elif mode == "des":
            T_htf_in = self.T_hot_c + 273.15
            T_sat_source = self.T_cool_c + 273.15      # condenser
        else:
            raise ValueError("mode must be 'ads' or 'des'")

        t_span = (0.0, self.t_half)
        t_eval = np.linspace(0.0, self.t_half, n_eval)
        sol = solve_ivp(
            self._bed_rhs, t_span, [T_bed0_K, w0],
            args=(mode, T_htf_in, T_sat_source),
            t_eval=t_eval, method="LSODA", rtol=1e-6, atol=1e-9, max_step=self.t_half / 10.0,
        )
        T_bed = sol.y[0]
        w = np.clip(sol.y[1], 0.0, self.W0)
        # rate of uptake (finite-diff on solution)
        dwdt = np.gradient(w, sol.t)
        return {"t": sol.t, "T_bed": T_bed, "w": w, "dwdt": dwdt,
                "mode": mode, "T_sat_source": T_sat_source}

    # ----- full cyclic simulation -------------------------------------
    def simulate(self, n_cycles=8, set_temps=None):
        """Run the chiller to cyclic steady state over n_cycles full cycles.

        A *full cycle* = one desorption half-cycle followed by one adsorption
        half-cycle for a given bed (the partner bed is mirror-imaged, so plant
        cooling output is continuous).  Returns time series plus integrated
        COP / SCP for the final (converged) cycle.
        """
        if set_temps:
            self.T_hot_c = set_temps.get("T_hot", self.T_hot_c)
            self.T_cool_c = set_temps.get("T_cool", self.T_cool_c)
            self.T_chilled_c = set_temps.get("T_chilled", self.T_chilled_c)
            self.t_half = set_temps.get("t_half_cycle", self.t_half)

        # initial state: bed near cool temperature, moderately loaded
        T_bed = self.T_cool_c + 273.15
        w = float(self.w_equilibrium(T_bed, self.T_chilled_c + 273.15))

        cycles = []
        for _ in range(int(n_cycles)):
            # desorption (regeneration) half-cycle
            des = self.run_half_cycle("des", T_bed, w)
            T_bed, w = des["T_bed"][-1], des["w"][-1]
            # adsorption (cooling) half-cycle
            ads = self.run_half_cycle("ads", T_bed, w)
            T_bed, w = ads["T_bed"][-1], ads["w"][-1]
            cycles.append((des, ads))

        des, ads = cycles[-1]  # converged cycle

        # cooling power during adsorption: refrigerant evaporated * h_fg
        # (dw/dt > 0 during adsorption => vapour drawn from evaporator)
        m_ref_rate_ads = self.m_sg * np.maximum(ads["dwdt"], 0.0)  # kg/s
        Q_evap = m_ref_rate_ads * self.h_fg                        # W
        # subtract sensible cooling of incoming vapour from chilled T to evap
        # (already at evaporator T; primary effect is latent) -> latent only

        # driving heat during desorption: hot-water duty into bed
        C_hw = self.m_dot_hw * self.cp_w_liq
        ntu = self.UA_bed / max(C_hw, 1e-9)
        eps = 1.0 - np.exp(-ntu)
        Q_des = eps * C_hw * ((self.T_hot_c + 273.15) - des["T_bed"])  # W, >0
        Q_des = np.maximum(Q_des, 0.0)

        # integrate over each half-cycle
        E_evap = np.trapezoid(Q_evap, ads["t"])     # J cooling delivered
        E_des = np.trapezoid(Q_des, des["t"])       # J driving heat
        cop_thermal = E_evap / E_des if E_des > 1e-9 else 0.0

        dur_full = ads["t"][-1] + des["t"][-1]
        Q_evap_mean = E_evap / self.t_half          # mean cooling power [W]
        scp = Q_evap_mean / self.m_sg               # specific cooling power W/kg

        # mass conservation: water desorbed vs adsorbed over the cycle
        dw_des = des["w"][0] - des["w"][-1]   # released during desorption
        dw_ads = ads["w"][-1] - ads["w"][0]   # taken up during adsorption

        return {
            "t_ads": ads["t"], "t_des": des["t"],
            "T_bed_ads": ads["T_bed"], "T_bed_des": des["T_bed"],
            "w_ads": ads["w"], "w_des": des["w"],
            "Q_evap": Q_evap, "Q_des": Q_des,
            "Q_evap_mean_W": Q_evap_mean,
            "cooling_power_kW": Q_evap_mean / 1000.0,
            "driving_heat_mean_kW": (E_des / self.t_half) / 1000.0,
            "thermal_COP": cop_thermal,
            "SCP_W_per_kg": scp,
            "cycle_time_s": dur_full,
            "dw_desorbed": dw_des, "dw_adsorbed": dw_ads,
            "E_evap_J": E_evap, "E_des_J": E_des,
            "n_cycles": int(n_cycles),
        }
