"""N_En_Phase 20 — auto-calibration driver tests.

Fixture: the single-bus storage site from the diff layer (2 gens +
battery). Parameters under calibration: the peaker's marginal cost and
the battery's discharge efficiency (the new η Jacobian block). Telemetry
is generated by the TRUE model; beliefs start wrong.
"""

from __future__ import annotations

import numpy as np
import pytest

from nexus_energy.autocal import AutoCalibrator, CalibrationReport, fit_params
from nexus_energy.diff import (
    StorageDispatchProblem,
    solve_storage_dispatch_with_sensitivities,
)

RIDGE = 1.0
DEMAND = np.array([60.0, 75.0, 95.0, 70.0])


def solve_site(theta, demand=DEMAND, extra_gen_mc=None):
    mc = [10.0, float(theta["mc_peaker"])]
    cap = [80.0, 80.0]
    if extra_gen_mc is not None:
        mc.append(extra_gen_mc)
        cap.append(50.0)
    prob = StorageDispatchProblem(
        marginal_cost=np.asarray(mc), capacity=np.asarray(cap),
        demand=np.asarray(demand, dtype=float),
        charge_eff=0.95, discharge_eff=float(theta["eta_d"]),
        power_limit=40.0, soc_max=200.0, soc_init=60.0, ridge=RIDGE)
    return solve_storage_dispatch_with_sensitivities(prob)


def jac(sol, theta, *, n_extra=0):
    cols = [
        sol.d_dispatch_d_mc[:, 1],            # ∂dispatch/∂mc_peaker
        sol.d_dispatch_d_discharge_eff,       # ∂dispatch/∂η_d
    ]
    for j in range(n_extra):
        cols.append(sol.d_dispatch_d_mc[:, 2 + j])
    return np.column_stack(cols)


TRUE = {"mc_peaker": 60.0, "eta_d": 0.95}


def test_two_param_recovery():
    observed = solve_site(TRUE).dispatch
    report = fit_params(
        lambda th: solve_site(th),
        observed,
        {"mc_peaker": (85.0, 20.0, 150.0), "eta_d": (0.70, 0.5, 1.0)},
        jac,
        n_iter=40,
    )
    print(f"\n[autocal] recovered {report.params_new} in "
          f"{report.n_solves} solves; loss {report.loss_history[-1]:.3e}")
    assert abs(report.params_new["mc_peaker"] - 60.0) < 1e-3 * 60.0
    assert abs(report.params_new["eta_d"] - 0.95) < 1e-3
    assert report.loss_history[-1] < 1e-10
    # Loss decreased monotonically over accepted steps.
    assert all(b <= a + 1e-12 for a, b in
               zip(report.loss_history, report.loss_history[1:]))


def test_gate_freezes_data_silent_param():
    # A third generator priced out of the market: its dispatch is pinned
    # at 0 in every period → its mc column is exactly zero → data-silent.
    observed = solve_site(TRUE, extra_gen_mc=500.0).dispatch
    report = fit_params(
        lambda th: solve_site(th, extra_gen_mc=float(th["mc_ghost"])),
        observed,
        {"mc_peaker": (75.0, 20.0, 150.0), "eta_d": (0.80, 0.5, 1.0),
         "mc_ghost": (500.0, 300.0, 900.0)},
        lambda s, th: jac(s, th, n_extra=1),
        n_iter=40,
    )
    assert report.frozen["mc_ghost"] is True
    assert report.params_new["mc_ghost"] == 500.0  # untouched
    assert abs(report.params_new["mc_peaker"] - 60.0) < 1e-2 * 60.0


def test_box_clipping():
    observed = solve_site(TRUE).dispatch
    # True eta_d (0.95) lies OUTSIDE the box → fit lands on the bound.
    report = fit_params(
        lambda th: solve_site(th),
        observed,
        {"mc_peaker": (60.0, 20.0, 150.0), "eta_d": (0.70, 0.5, 0.85)},
        jac,
        n_iter=40,
    )
    assert report.params_new["eta_d"] == pytest.approx(0.85, abs=1e-9)


def test_max_rel_step_limits_slew():
    observed = solve_site(TRUE).dispatch
    report = fit_params(
        lambda th: solve_site(th),
        observed,
        {"mc_peaker": (120.0, 20.0, 150.0), "eta_d": (0.60, 0.5, 1.0)},
        jac,
        n_iter=1,
        max_rel_step=0.25,
    )
    assert abs(report.params_new["mc_peaker"] - 120.0) <= 0.25 * 120.0 + 1e-9
    assert abs(report.params_new["eta_d"] - 0.60) <= 0.25 * 0.60 + 1e-9


def test_autocalibrator_tracks_drift():
    # True η_d degrades linearly 0.95 → 0.85 over 10 windows; the
    # calibrator (seeded right once) follows within its slew limit.
    cal = AutoCalibrator(
        solution_factory=lambda window, th: solve_site(th, demand=window["demand"]),
        jacobian_fn=jac,
        observed_fn=lambda window: window["observed"],
        params={"mc_peaker": (60.0, 20.0, 150.0), "eta_d": (0.95, 0.5, 1.0)},
        update_every=2,
        n_iter_per_cycle=8,
        max_rel_step=0.25,
    )
    rng = np.random.default_rng(5)
    errs = []
    for k in range(10):
        true_eta = 0.95 - 0.01 * (k + 1)
        demand = DEMAND + rng.normal(0, 2, DEMAND.size)
        observed = solve_site({"mc_peaker": 60.0, "eta_d": true_eta},
                              demand=demand).dispatch
        rep = cal.step({"demand": demand, "observed": observed})
        if k % 2 == 0:
            assert isinstance(rep, CalibrationReport)
        else:
            assert rep is None  # skipped cycle (update_every=2)
        errs.append(abs(cal.believed["eta_d"] - true_eta))
    print(f"\n[autocal-drift] final believed eta_d={cal.believed['eta_d']:.4f} "
          f"true=0.85; per-window |err|={[round(e, 4) for e in errs]}")
    # Tracks the drift closely by the end.
    assert errs[-1] < 0.02


# ---------------------------------------------------------------------------
# Toggle / operator-control API
# ---------------------------------------------------------------------------

def _make_cal(**kw):
    return AutoCalibrator(
        solution_factory=lambda w, th: solve_site(th, demand=w["demand"]),
        jacobian_fn=jac,
        observed_fn=lambda w: w["observed"],
        params={"mc_peaker": (85.0, 20.0, 150.0), "eta_d": (0.70, 0.5, 1.0)},
        n_iter_per_cycle=10, **kw)


def _window():
    observed = solve_site(TRUE).dispatch
    return {"demand": DEMAND, "observed": observed}


def test_disable_enable_toggle():
    cal = _make_cal()
    cal.disable()
    assert cal.step(_window()) is None
    assert cal.believed == {"mc_peaker": 85.0, "eta_d": 0.70}  # untouched
    cal.enable()
    rep = cal.step(_window())
    assert rep is not None
    assert abs(cal.believed["eta_d"] - 0.70) > 1e-3  # moved once enabled


def test_lock_param_holds_value_while_others_fit():
    cal = _make_cal(max_rel_step=1.0)
    cal.lock_param("eta_d")
    rep = cal.step(_window())
    assert rep.params_new["eta_d"] == 0.70          # held exactly
    assert rep.frozen["eta_d"] is True               # reported as held
    assert abs(rep.params_new["mc_peaker"] - 60.0) < 1.0  # others still fit
    cal.unlock_param("eta_d")
    cal.step(_window())
    assert abs(cal.believed["eta_d"] - 0.70) > 1e-3  # free again


def test_set_param_manual_override_and_lock():
    cal = _make_cal()
    cal.set_param("eta_d", 0.93, lock=True)
    assert cal.believed["eta_d"] == 0.93
    cal.step(_window())
    assert cal.believed["eta_d"] == 0.93             # locked against auto-fit
    cal.set_param("eta_d", 2.0)                      # clamped to box
    assert cal.believed["eta_d"] == 1.0
    with pytest.raises(KeyError):
        cal.set_param("nope", 1.0)


def test_all_locked_skips_fit():
    cal = _make_cal()
    cal.lock_param("eta_d")
    cal.lock_param("mc_peaker")
    assert cal.step(_window()) is None


# ---------------------------------------------------------------------------
# 20.x.1 — separate η_c / η_d identification from SOC-trace telemetry
# ---------------------------------------------------------------------------

def solve_site_split(theta, demand=DEMAND):
    # soc_init=0 forces the battery to CHARGE before it can discharge, so
    # both efficiencies are exercised in the telemetry window.
    prob = StorageDispatchProblem(
        marginal_cost=np.array([10.0, 60.0]), capacity=np.array([80.0, 80.0]),
        demand=np.asarray(demand, dtype=float),
        charge_eff=float(theta["eta_c"]), discharge_eff=float(theta["eta_d"]),
        power_limit=40.0, soc_max=200.0, soc_init=0.0, ridge=RIDGE)
    return solve_storage_dispatch_with_sensitivities(prob)


def test_eta_split_unidentifiable_from_dispatch_alone():
    """Sanity for the deferral rationale: dispatch-only residual leaves the
    (η_c, η_d) split ill-determined — the fit may land on a different point
    with (near-)matching dispatch, or the gate may freeze a direction."""
    demand = np.array([30.0, 30.0, 95.0, 90.0])
    true = {"eta_c": 0.97, "eta_d": 0.90}
    obs = solve_site_split(true, demand=demand).dispatch
    rep = fit_params(
        lambda th: solve_site_split(th, demand=demand), obs,
        {"eta_c": (0.80, 0.5, 1.0), "eta_d": (0.80, 0.5, 1.0)},
        lambda s, th: np.column_stack(
            [s.d_dispatch_d_charge_eff, s.d_dispatch_d_discharge_eff]),
        n_iter=60)
    # Dispatch may be matched well...
    assert rep.loss_history[-1] < 1e-6
    # ...but we don't assert the individual etas: only their effect is pinned.


def test_eta_split_recovered_with_soc_trace():
    """With SOC in the residual, η_c and η_d are SEPARATELY identifiable."""
    demand = np.array([30.0, 30.0, 95.0, 90.0])
    true = {"eta_c": 0.97, "eta_d": 0.90}
    sol_true = solve_site_split(true, demand=demand)
    assert sol_true.charge.max() > 1.0 and sol_true.discharge.max() > 1.0
    obs = np.concatenate([sol_true.dispatch.reshape(-1), sol_true.soc])

    def residual(sol):
        return np.concatenate(
            [sol.dispatch.reshape(-1), sol.soc]) - obs

    def jacobian(sol, theta):
        col_c = np.concatenate(
            [sol.d_dispatch_d_charge_eff, sol.d_soc_d_charge_eff])
        col_d = np.concatenate(
            [sol.d_dispatch_d_discharge_eff, sol.d_soc_d_discharge_eff])
        return np.column_stack([col_c, col_d])

    rep = fit_params(
        lambda th: solve_site_split(th, demand=demand),
        obs,
        {"eta_c": (0.80, 0.5, 1.0), "eta_d": (0.80, 0.5, 1.0)},
        jacobian,
        residual_fn=residual,
        n_iter=60)
    print(f"\n[eta-split] recovered eta_c={rep.params_new['eta_c']:.5f} "
          f"(true 0.97), eta_d={rep.params_new['eta_d']:.5f} (true 0.90); "
          f"{rep.n_solves} solves")
    assert abs(rep.params_new["eta_c"] - 0.97) < 1e-3
    assert abs(rep.params_new["eta_d"] - 0.90) < 1e-3


# ---------------------------------------------------------------------------
# 20.x.2 — noise-aware MHE (smoothing + outlier rejection)
# ---------------------------------------------------------------------------

def test_noise_smoothing_beats_raw_fits():
    """With noisy telemetry, EMA-smoothed beliefs track the constant true
    value with LOWER error spread than per-window raw fits."""
    rng = np.random.default_rng(9)
    true = {"mc_peaker": 60.0, "eta_d": 0.95}

    def windows(n):
        for _ in range(n):
            demand = DEMAND + rng.normal(0, 2, DEMAND.size)
            obs = solve_site(true, demand=demand).dispatch \
                + rng.normal(0, 1.5, (2, DEMAND.size))
            yield {"demand": demand, "observed": obs}

    def run(smooth):
        cal = AutoCalibrator(
            solution_factory=lambda w, th: solve_site(th, demand=w["demand"]),
            jacobian_fn=jac, observed_fn=lambda w: w["observed"],
            params={"mc_peaker": (60.0, 20.0, 150.0),
                    "eta_d": (0.90, 0.5, 1.0)},
            n_iter_per_cycle=6, max_rel_step=0.5,
            noise_std=1.5, smooth=smooth)
        ests = []
        for w in windows(15):
            cal.step(w)
            ests.append(cal.believed["eta_d"])
        return np.array(ests)

    rng = np.random.default_rng(9)
    raw = run(smooth=1.0)
    rng = np.random.default_rng(9)
    smoothed = run(smooth=0.3)
    err_raw = np.abs(raw[5:] - 0.95)
    err_smooth = np.abs(smoothed[5:] - 0.95)
    print(f"\n[mhe] mean |err| raw={err_raw.mean():.4f} "
          f"smoothed={err_smooth.mean():.4f}")
    assert err_smooth.mean() <= err_raw.mean() + 1e-6
    assert err_smooth.mean() < 0.02


def test_outlier_window_rejected():
    cal = AutoCalibrator(
        solution_factory=lambda w, th: solve_site(th, demand=w["demand"]),
        jacobian_fn=jac, observed_fn=lambda w: w["observed"],
        params={"mc_peaker": (60.0, 20.0, 150.0), "eta_d": (0.95, 0.5, 1.0)},
        n_iter_per_cycle=6, noise_std=1.5, smooth=0.5)
    garbage = {"demand": DEMAND,
               "observed": np.full((2, DEMAND.size), 500.0)}  # sensor fault
    rep = cal.step(garbage)
    assert "REJECTED" in rep.message
    assert cal.believed == {"mc_peaker": 60.0, "eta_d": 0.95}  # untouched
