"""
EC200 -- Oxy-Fuel Combustion Capture -- F1a Capture & Energy Model (ALGEBRAIC)

Semi-empirical, algebraic model of an oxy-fuel combustion CO2 capture island.
Fuel is burned in nearly-pure O2 from an Air Separation Unit (ASU) rather than
air, so the flue gas is mostly CO2 + H2O. CO2 is recovered by simple water
condensation (no chemical solvent). A fraction of the flue gas is recycled to
moderate flame temperature. The dominant energy penalty is the ASU O2
production (cryogenic, ~200-240 kWh per tonne O2) plus CO2 compression to
pipeline pressure (~90-120 kWh/tCO2).

Algebraic relations (fitted / stoichiometric):
    O2 demand          : stoichiometric from fuel C/H/S + excess O2 ratio
    capture rate       : near-complete (>0.90), set by purification/condensation
    ASU penalty        : w_ASU [kWh/tO2] * m_O2  (load- and purity-dependent fit)
    compression penalty: w_comp [kWh/tCO2] * m_CO2
    net efficiency drop : (P_ASU + P_comp) / P_gross_thermal  ->  delta_eta

References:
    Buhre, B.J.P., Elliott, L.K., Sheng, C.D., Gupta, R.P., Wall, T.F. (2005).
        Oxy-fuel combustion technology for coal-fired power generation.
        Progress in Energy and Combustion Science, 31(4), 283-307.
    Toftegaard, M.B., Brix, J., Jensen, P.A., Glarborg, P., Jensen, A.D. (2010).
        Oxy-fuel combustion of solid fuels.
        Progress in Energy and Combustion Science, 36(5), 581-625.
"""

import numpy as np


class OxyFuelF1a:
    """Oxy-fuel combustion capture -- algebraic capture & energy-penalty model."""

    def __init__(self, params: dict):
        u = params["unit"]
        # Fuel ultimate analysis (mass fractions, dry ash-free basis)
        self.w_C = u["fuel_C"]["value"]
        self.w_H = u["fuel_H"]["value"]
        self.w_S = u["fuel_S"]["value"]
        self.w_O = u["fuel_O"]["value"]
        self.LHV = u["fuel_LHV"]["value"]              # MJ/kg
        # ASU / compression specific energies
        self.w_ASU_ref = u["asu_specific_energy"]["value"]    # kWh/tO2 at design purity
        self.w_comp_ref = u["compression_specific_energy"]["value"]  # kWh/tCO2
        self.O2_purity = u["o2_purity"]["value"]       # mol/mol from ASU
        self.excess_O2 = u["excess_o2_ratio"]["value"] # lambda - 1
        self.capture_design = u["capture_rate_design"]["value"]
        self.MW_C = u["MW_C"]["value"]
        self.MW_O2 = u["MW_O2"]["value"]
        self.MW_H = u["MW_H"]["value"]
        self.MW_S = u["MW_S"]["value"]
        self.MW_CO2 = u["MW_CO2"]["value"]

    # ------------------------------------------------------------------
    # Stoichiometric O2 demand (kg O2 per kg fuel)
    # ------------------------------------------------------------------
    def stoichiometric_o2(self):
        """
        Stoichiometric O2 mass per kg fuel (kg O2 / kg fuel).
        C + O2 -> CO2          (1 mol O2 / mol C)
        H + 1/4 O2 -> 1/2 H2O  (0.25 mol O2 / mol H atom)
        S + O2 -> SO2          (1 mol O2 / mol S)
        minus O2 already in fuel.
        Standard combustion stoichiometry (Buhre 2005).
        """
        molO2 = (self.w_C / self.MW_C
                 + 0.25 * self.w_H / self.MW_H
                 + self.w_S / self.MW_S
                 - 0.5 * self.w_O / self.MW_O2)        # O in fuel as O atoms
        return molO2 * self.MW_O2  # kg O2 / kg fuel

    def o2_demand(self, fuel_kgs, load=1.0):
        """
        Actual O2 supplied (kg/s), including excess O2 (lambda).
        Excess O2 ratio modestly higher at part load (worse mixing).
        """
        fuel = np.asarray(fuel_kgs, dtype=float)
        load = np.asarray(load, dtype=float)
        excess = self.excess_O2 * (1.0 + 0.3 * (1.0 - load))  # more excess at low load
        return fuel * self.stoichiometric_o2() * (1.0 + excess)

    # ------------------------------------------------------------------
    # CO2 produced and captured
    # ------------------------------------------------------------------
    def co2_produced(self, fuel_kgs):
        """CO2 generated by combustion (kg/s) -- all fuel carbon -> CO2."""
        fuel = np.asarray(fuel_kgs, dtype=float)
        molC = self.w_C / self.MW_C                  # mol C / kg fuel
        return fuel * molC * self.MW_CO2

    def capture_rate(self, co2_purity_dry):
        """
        CO2 capture fraction. Oxy-fuel captures nearly all CO2 because the
        whole concentrated stream goes to compression; small losses are the
        CO2 vented with the non-condensable purge (O2/N2/Ar) during
        purification. Higher purity target -> slightly more venting.
        Fit: CR = CR_design - 0.12*(purity - 0.90), bounded.
        """
        p = np.asarray(co2_purity_dry, dtype=float)
        cr = self.capture_design - 0.12 * (p - 0.90)
        return np.clip(cr, 0.85, 0.99)

    def co2_captured(self, fuel_kgs, co2_purity_dry=0.95):
        cr = self.capture_rate(co2_purity_dry)
        return self.co2_produced(fuel_kgs) * cr

    # ------------------------------------------------------------------
    # Energy penalties
    # ------------------------------------------------------------------
    def asu_specific_energy(self, o2_purity=None, load=1.0):
        """
        ASU specific energy (kWh / tonne O2). Rises with purity (cryogenic
        distillation column reflux) and at part load (off-design compressor
        efficiency). Buhre (2005): ~200-240 kWh/tO2 for 95-99.5% O2.
        """
        if o2_purity is None:
            o2_purity = self.O2_purity
        o2_purity = np.asarray(o2_purity, dtype=float)
        load = np.asarray(load, dtype=float)
        purity_factor = 1.0 + 1.5 * (o2_purity - 0.95)      # +~7.5%/5pts purity
        load_factor = 1.0 + 0.15 * (1.0 - load)             # part-load penalty
        return self.w_ASU_ref * purity_factor * load_factor

    def compression_specific_energy(self, capture_rate_val=None):
        """CO2 compression specific energy (kWh/tCO2) to ~110 bar pipeline."""
        return self.w_comp_ref

    def asu_power(self, fuel_kgs, load=1.0, o2_purity=None):
        """ASU electrical power (MW)."""
        m_o2 = self.o2_demand(fuel_kgs, load)                # kg/s
        w = self.asu_specific_energy(o2_purity, load)        # kWh/tO2
        # kg/s -> t/s = /1000 ; kWh/t * t/s = kW*h/s ; *3600 -> kW? No:
        # kWh/t * t/s = kWh/s = kW*3600... correct unit chain:
        # m_o2 [kg/s] /1000 [t/kg] * w [kWh/t] = kWh/s ; 1 kWh/s = 3600 kW = 3.6 MW
        return m_o2 / 1000.0 * w * 3.6                        # MW

    def compression_power(self, fuel_kgs, co2_purity_dry=0.95):
        """CO2 compression electrical power (MW)."""
        m_co2 = self.co2_captured(fuel_kgs, co2_purity_dry)  # kg/s
        w = self.compression_specific_energy()               # kWh/tCO2
        return m_co2 / 1000.0 * w * 3.6                       # MW

    def gross_thermal_power(self, fuel_kgs):
        """Fuel thermal input (MW) = LHV * fuel rate."""
        fuel = np.asarray(fuel_kgs, dtype=float)
        return fuel * self.LHV                                # MJ/kg * kg/s = MW

    def efficiency_penalty(self, fuel_kgs, load=1.0, o2_purity=None,
                           co2_purity_dry=0.95, base_efficiency=0.40):
        """
        Net efficiency drop (percentage points) from capture parasitic loads.
        delta_eta = base_eff * (P_parasitic / P_gross_electric)
        where P_gross_electric = base_eff * P_thermal.
        Returns delta_eta as an absolute drop in efficiency (e.g. 0.09 = 9 pts).
        Typical oxy-fuel penalty 8-12 points (Buhre 2005, Toftegaard 2010).
        """
        P_asu = self.asu_power(fuel_kgs, load, o2_purity)
        P_comp = self.compression_power(fuel_kgs, co2_purity_dry)
        P_thermal = self.gross_thermal_power(fuel_kgs)
        P_gross_elec = base_efficiency * P_thermal
        parasitic_frac = (P_asu + P_comp) / np.maximum(P_gross_elec, 1e-9)
        return base_efficiency * parasitic_frac              # absolute pts drop

    def net_efficiency(self, fuel_kgs, load=1.0, o2_purity=None,
                       co2_purity_dry=0.95, base_efficiency=0.40):
        """Net plant efficiency after capture penalty."""
        d = self.efficiency_penalty(fuel_kgs, load, o2_purity,
                                    co2_purity_dry, base_efficiency)
        return np.clip(base_efficiency - d, 0.0, base_efficiency)
