"""
EC200 -- Oxy-Fuel Combustion Capture -- F1a Capture & Energy Model
Standardised predict() / get_info() interface.
"""

import json
import os
import sys
import numpy as np

sys.path.insert(0, os.path.dirname(__file__))
from model import OxyFuelF1a

_PARAMS_PATH = os.path.join(os.path.dirname(__file__), "..", "data", "parameters.json")


def _load_params():
    with open(_PARAMS_PATH, "r") as f:
        return json.load(f)


class ComponentModel:
    """Standardised wrapper for EC200 oxy-fuel F1a capture & energy model."""

    component_id = "EC200"
    component_name = "Oxy-Fuel Combustion Capture"
    fidelity = "F1a -- Capture & Energy Model (algebraic)"
    version = "1.0.0"

    def __init__(self, params: dict = None):
        self._raw = _load_params()
        if params:
            self._raw["unit"].update(params)
        self._model = OxyFuelF1a(self._raw)

    def predict(self, inputs: dict) -> dict:
        """
        Predict oxy-fuel capture-island performance.

        inputs:
            fuel_rate      : float or array  (kg/s, 1-100)
            load           : float or array  (0.4-1.0), default 1.0
            o2_purity      : float or array  (0.90-0.995), default 0.95
            co2_purity_dry : float or array  (0.90-0.99), default 0.95
            base_efficiency: float           (0.30-0.45), default 0.40

        returns:
            o2_demand_kgs       : O2 supplied (kg/s)
            co2_produced_kgs    : CO2 generated by combustion (kg/s)
            co2_captured_kgs    : CO2 captured (kg/s)
            capture_rate        : capture fraction (-)
            asu_power_mw        : ASU electrical power (MW)
            compression_power_mw: CO2 compression power (MW)
            parasitic_power_mw  : total parasitic electrical power (MW)
            efficiency_drop_pts : net efficiency drop (fraction, e.g. 0.09)
            net_efficiency      : net plant efficiency after capture (-)
        """
        fuel = np.asarray(inputs["fuel_rate"], dtype=float)
        load = np.asarray(inputs.get("load", 1.0), dtype=float)
        o2p = np.asarray(inputs.get("o2_purity", self._model.O2_purity), dtype=float)
        co2p = np.asarray(inputs.get("co2_purity_dry", 0.95), dtype=float)
        base_eff = float(inputs.get("base_efficiency", 0.40))

        o2 = self._model.o2_demand(fuel, load)
        co2_prod = self._model.co2_produced(fuel)
        cr = self._model.capture_rate(co2p)
        co2_cap = self._model.co2_captured(fuel, co2p)
        p_asu = self._model.asu_power(fuel, load, o2p)
        p_comp = self._model.compression_power(fuel, co2p)
        d_eta = self._model.efficiency_penalty(fuel, load, o2p, co2p, base_eff)
        eta_net = self._model.net_efficiency(fuel, load, o2p, co2p, base_eff)

        return {
            "o2_demand_kgs": o2,
            "co2_produced_kgs": co2_prod,
            "co2_captured_kgs": co2_cap,
            "capture_rate": cr,
            "asu_power_mw": p_asu,
            "compression_power_mw": p_comp,
            "parasitic_power_mw": p_asu + p_comp,
            "efficiency_drop_pts": d_eta,
            "net_efficiency": eta_net,
        }

    def get_info(self) -> dict:
        return {
            "component_id": self.component_id,
            "component_name": self.component_name,
            "fidelity": self.fidelity,
            "version": self.version,
            "description": (
                "Algebraic oxy-fuel capture model. O2 demand from fuel "
                "stoichiometry, near-complete CO2 capture by condensation, "
                "energy penalty = ASU (~220 kWh/tO2) + CO2 compression "
                "(~100 kWh/tCO2)."
            ),
            "inputs": {
                "fuel_rate": {"unit": "kg/s", "range": [1.0, 100.0]},
                "load": {"unit": "-", "range": [0.4, 1.0], "default": 1.0},
                "o2_purity": {"unit": "mol/mol", "range": [0.90, 0.995], "default": 0.95},
                "co2_purity_dry": {"unit": "mol/mol", "range": [0.90, 0.99], "default": 0.95},
                "base_efficiency": {"unit": "-", "range": [0.30, 0.45], "default": 0.40},
            },
            "outputs": {
                "o2_demand_kgs": "kg/s",
                "co2_produced_kgs": "kg/s",
                "co2_captured_kgs": "kg/s",
                "capture_rate": "-",
                "asu_power_mw": "MW",
                "compression_power_mw": "MW",
                "parasitic_power_mw": "MW",
                "efficiency_drop_pts": "-",
                "net_efficiency": "-",
            },
            "source": self._raw.get("source", ""),
            "license": "BSD-3",
        }


if __name__ == "__main__":
    m = ComponentModel()
    r = m.predict({"fuel_rate": 50.0, "load": 1.0, "o2_purity": 0.95,
                   "co2_purity_dry": 0.95, "base_efficiency": 0.40})
    print("EC200 Oxy-Fuel F1a -- fuel=50 kg/s, load=100%, O2=95%:")
    print(f"  O2 demand          = {float(r['o2_demand_kgs']):.2f} kg/s")
    print(f"  CO2 produced       = {float(r['co2_produced_kgs']):.2f} kg/s")
    print(f"  CO2 captured       = {float(r['co2_captured_kgs']):.2f} kg/s")
    print(f"  Capture rate       = {float(r['capture_rate']):.3f}")
    print(f"  ASU power          = {float(r['asu_power_mw']):.1f} MW")
    print(f"  Compression power  = {float(r['compression_power_mw']):.1f} MW")
    print(f"  Efficiency drop    = {float(r['efficiency_drop_pts'])*100:.1f} pts")
    print(f"  Net efficiency     = {float(r['net_efficiency'])*100:.1f} %")
    info = m.get_info()
    print(f"  {info['component_id']} / {info['fidelity']}")
